export const ERROR_CODES = {
  BAD_REQUEST: 'BAD_REQUEST',
  UNAUTHORIZED: 'UNAUTHORIZED',
  FORBIDDEN: 'FORBIDDEN',
  NOT_FOUND: 'NOT_FOUND',
  INTERNAL_SERVER: 'INTERNAL_SERVER'
} as const

export type ErrorCode = typeof ERROR_CODES[keyof typeof ERROR_CODES]
