export const SENDING_PATTERN = {
  PASSWORD_CHANGE_NOTIFICATION: 'PASSWORD_CHANGE_NOTIFICATION',
  ACCOUNT_DELETE_NOTIFICATION: 'ACCOUNT_DELETE_NOTIFICATION',
} as const
export type SENDING_PATTERN_TYPE = (typeof SENDING_PATTERN)[keyof typeof SENDING_PATTERN]
