export const ERROR_CODES = {
  SOURCE_PATTERN_NOT_FOUND: 'SOURCE_PATTERN_NOT_FOUND',
  BUSINESS_LOGIC_ERROR: 'BUSINESS_LOGIC_ERROR',
} as const
export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES]

export const ERROR_CATEGORIES = {
  BUSINESS_LOGIC_ERROR: 'BUSINESS_LOGIC_ERROR',
  SYSTEM_ERROR: 'SYSTEM_ERROR',
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  NETWORK_ERROR: 'NETWORK_ERROR',
} as const
export type ErrorCategory = (typeof ERROR_CATEGORIES)[keyof typeof ERROR_CATEGORIES]
