export const ERROR_CODES = {
  INVALID_REQUEST: 'INVALID_REQUEST',

  SOURCE_PATTERN_NOT_FOUND: 'SOURCE_PATTERN_NOT_FOUND',

  RECORD_NOT_FOUND: 'RECORD_NOT_FOUND',
  RECORD_NOT_ACTIVE: 'RECORD_NOT_ACTIVE',
  DATABASE_QUERY_ERROR: 'DATABASE_QUERY_ERROR',
  DATABASE_FUNCTION_ERROR: 'DATABASE_FUNCTION_ERROR',

  LLM_GENERATE_CONTENT_EMPTY: 'LLM_GENERATE_CONTENT_EMPTY',
  LLM_GENERATE_CONTENT_INVALID_FORMAT: 'LLM_GENERATE_CONTENT_INVALID_FORMAT',
  LLM_GENERATE_CONTENT_INVALID_SCHEMA: 'LLM_GENERATE_CONTENT_INVALID_SCHEMA',

  MAX_RETRY_ERROR: 'LLM_GENERATE_CONTENT_MAX_RETRY_ERROR',

  UNEXPECTED_ERROR: 'UNEXPECTED_ERROR',
} as const
export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES]

export const ERROR_CATEGORIES = {
  BUSINESS_LOGIC_ERROR: 'BUSINESS_LOGIC_ERROR',
  SYSTEM_ERROR: 'SYSTEM_ERROR',
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  NETWORK_ERROR: 'NETWORK_ERROR',
} as const
export type ErrorCategory = (typeof ERROR_CATEGORIES)[keyof typeof ERROR_CATEGORIES]

export const DATABASE_QUERY_OPERATION = {
  COUNT: 'COUNT',
  SELECT: 'SELECT',
  INSERT: 'INSERT',
  UPDATE: 'UPDATE',
  DELETE: 'DELETE',
} as const
export type DatabaseQueryOperation =
  (typeof DATABASE_QUERY_OPERATION)[keyof typeof DATABASE_QUERY_OPERATION]
