name: Deploy App

on:
  push: # PR をマージしたときも、GitHub 上では「マージ先ブランチへの push」が発生
    branches:
      - prod
      - main
      - stage
      - develop
      - feat-**
  pull_request:
    branches: [main, prod, stage]

permissions:
  id-token: write # OIDCトークン取得を許可
  contents: read # Githubリポジトリの読み取り権限

concurrency:
  group: deploy-${{ github.ref }}
  cancel-in-progress: true

env:
  ENVIRONMENT: ${{ github.ref == 'refs/heads/prod' && 'prod' || github.ref == 'refs/heads/stage' && 'stage' || 'dev' }}
  APP_DIR: frontend
  # ↓　Terraformからsupabaseにアクセスする用
  TF_VAR_supabase_access_token: ${{secrets.SUPABASE_ACCESS_TOKEN}}
  TF_VAR_supabase_org_id: ${{secrets.SUPABASE_ORG_ID}}
  TF_VAR_supabase_database_password: ${{secrets.SUPABASE_DATABASE_PASSWORD}}
  TF_VAR_supabase_database_env: ${{ github.ref == 'refs/heads/prod' && 'prod' || 'dev' }}
  # ↑　Terraformからsupabaseにアクセスする用
  SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}

  # ↓　Supabase
  SUPABASE_PROJECT_ID: ${{ github.ref == 'refs/heads/prod' && secrets.SUPABASE_PROJECT_ID_PROD || secrets.SUPABASE_PROJECT_ID_DEV }}
  SUPABASE_URL: ${{ github.ref == 'refs/heads/prod' && secrets.SUPABASE_URL_PROD || secrets.SUPABASE_URL_DEV }}
  SUPABASE_DATABASE_URL: ${{ github.ref == 'refs/heads/prod' && secrets.SUPABASE_DATABASE_URL_PROD || secrets.SUPABASE_DATABASE_URL_DEV }}
  SUPABASE_SESSION_POOLER_URL: ${{ github.ref == 'refs/heads/prod' && secrets.SUPABASE_SESSION_POOLER_URL_PROD || secrets.SUPABASE_SESSION_POOLER_URL_DEV }}
  SUPABASE_ANON_KEY: ${{ github.ref == 'refs/heads/prod' && secrets.SUPABASE_ANON_KEY_PROD || secrets.SUPABASE_ANON_KEY_DEV }}
  SUPABASE_SERVICE_ROLE_KEY: ${{ github.ref == 'refs/heads/prod' && secrets.SUPABASE_SERVICE_ROLE_KEY_PROD || secrets.SUPABASE_SERVICE_ROLE_KEY_DEV }}
  SUPABASE_JWT_SECRET: ${{ github.ref == 'refs/heads/prod' && secrets.SUPABASE_JWT_SECRET_PROD || secrets.SUPABASE_JWT_SECRET_DEV }}
  # ↑　Supabase

  # ↓　メール送信用
  RESEND_API_KEY: ${{ github.ref == 'refs/heads/prod' && secrets.RESEND_API_KEY_PROD || secrets.RESEND_API_KEY_DEV }}
  FROM_EMAIL: ${{ github.ref == 'refs/heads/prod' && vars.FROM_EMAIL_PROD || vars.FROM_EMAIL_PROD }}
  SUPPORT_EMAIL: ${{ github.ref == 'refs/heads/prod' && vars.SUPPORT_EMAIL_PROD || vars.SUPPORT_EMAIL_DEV }}
  # ↑　メール送信用

  # ↓　Descope
  DESCOPE_PROJECT_ID: ${{ github.ref == 'refs/heads/prod' && secrets.DESCOPE_PROJECT_ID_PROD || secrets.DESCOPE_PROJECT_ID_DEV }}
  DESCOPE_ISSUER: ${{ github.ref == 'refs/heads/prod' && vars.DESCOPE_ISSUER_PROD || vars.DESCOPE_ISSUER_DEV }}
  DESCOPE_AUDIENCE: ${{ github.ref == 'refs/heads/prod' && vars.DESCOPE_AUDIENCE_PROD || vars.DESCOPE_AUDIENCE_DEV }}
  DESCOPE_JWKS_URI: ${{ github.ref == 'refs/heads/prod' && vars.DESCOPE_JWKS_URI_PROD || vars.DESCOPE_JWKS_URI_DEV }}
  DESCOPE_MGMT_KEY: ${{ github.ref == 'refs/heads/prod' && secrets.DESCOPE_MGMT_KEY_PROD || secrets.DESCOPE_MGMT_KEY_DEV }}
  # ↑　Descope

jobs:
  setup: # 開発環境の準備とNext.jsのビルド
    name: Setup & Build (Next.js)
    runs-on: ubuntu-latest # GitHub提供の Ubuntu環境の仮想マシンで実行
    steps:
      - name: Checkout repository # GitHubリポジトリのソースコードを 仮想マシンにダウンロード
        uses: actions/checkout@v3

      - name: Install Node.js # Next.js 推奨の Node.js 18 をインストール
        uses: actions/setup-node@v4
        with:
          node-version: "22"
          cache: npm
          cache-dependency-path: ./frontend/package-lock.json

      - name: Create frontend environment file # .envファイルを生成
        run: |
          cat <<EOF > .env
          NEXT_PUBLIC_SUPABASE_URL=${{env.SUPABASE_URL}}
          NEXT_PUBLIC_SUPABASE_ANON_KEY=${{env.SUPABASE_ANON_KEY}}
          NEXT_PUBLIC_SUPABASE_PROJECT_ID=${{env.SUPABASE_PROJECT_ID}}
          NEXT_PUBLIC_DESCOPE_PROJECT_ID=${{env.DESCOPE_PROJECT_ID}}
          SUPABASE_SERVICE_ROLE_KEY=${{env.SUPABASE_SERVICE_ROLE_KEY}}
          SUPABASE_JWT_SECRET=${{env.SUPABASE_JWT_SECRET}}
          RESEND_API_KEY=${{env.RESEND_API_KEY}}
          FROM_EMAIL=${{env.FROM_EMAIL}}
          SUPPORT_EMAIL=${{env.SUPPORT_EMAIL}}
          DESCOPE_ISSUER=${{env.DESCOPE_ISSUER}}
          DESCOPE_AUDIENCE=${{env.DESCOPE_AUDIENCE}}
          DESCOPE_JWKS_URI=${{env.DESCOPE_JWKS_URI}}
          DESCOPE_MGMT_KEY=${{env.DESCOPE_MGMT_KEY}}
          EOF
        working-directory: ${{env.APP_DIR}}

      - name: Install dependencies # 依存パッケージのインストール
        run: npm install
        working-directory: ${{env.APP_DIR}}

      # - name: Run Tests # テスト実行
      #   run: npm test
      #   working-directory: frontend

      - name: Build Next.js App # Next.jsアプリケーションをビルド
        run: npm run build
        working-directory: ${{env.APP_DIR}}

  # 本番環境のSupabaseプロジェクトは手動で作成する
  #　それ以外の環境については全自動でTerraformにて管理する
  deploy: # AWSリソースの作成とVercelへのデプロイ
    name: Deploy Infrastructure and App
    runs-on: ubuntu-latest # GitHub提供の Ubuntu環境の仮想マシンで実行
    needs: setup # 「setup」ジョブが成功した場合にのみ実行

    steps:
      - name: Checkout repository # 「setup」ジョブとは異なるランナーが使用されるので再度ソースコードをダウンロード
        uses: actions/checkout@v3

      - name: Configure AWS Credentials # Github ActionsのAWS認証
        uses: aws-actions/configure-aws-credentials@v2 # GitHub公式のAWS認証アクション を使う（OIDC経由の認証）
        with:
          role-to-assume: arn:aws:iam::${{secrets.TF_AWS_ACCOUNT_ID}}:role/GitHubActionsTerraformRole
          role-session-name: GitHubActionsTerraformSession
          aws-region: ap-northeast-1

      - name: Setup Terraform # Terraform1.5.0をインストール
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.5.0

      - name: Initialize Terraform # Terraform を 初期化 し、リモートバックエンド（S3など）やプロバイダー情報（AWSなど）を取得
        run: terraform init
        working-directory: infra/env/${{env.ENVIRONMENT}}

      - name: Plan Terraform # AWSにどのようなリソースが作成・変更されるかを確認
        run: terraform plan
        working-directory: infra/env/${{env.ENVIRONMENT}}

      - name: Apply Terraform # リソース作成(環境変数としてAWSの認証情報を設定)
        run: terraform apply -auto-approve
        working-directory: infra/env/${{env.ENVIRONMENT}}

      - name: Setup Supabase CLI # Supabase CLIをインストール
        uses: supabase/setup-cli@v1
        with:
          version: latest

      - name: Create frontend environment file # .envファイルを生成
        run: |
          cat <<EOF > .env
          NEXT_PUBLIC_SUPABASE_URL=${{env.SUPABASE_URL}}
          NEXT_PUBLIC_SUPABASE_ANON_KEY=${{env.SUPABASE_ANON_KEY}}
          NEXT_PUBLIC_SUPABASE_PROJECT_ID=${{env.SUPABASE_PROJECT_ID}}
          NEXT_PUBLIC_DESCOPE_PROJECT_ID=${{env.DESCOPE_PROJECT_ID}}
          SUPABASE_SERVICE_ROLE_KEY=${{env.SUPABASE_SERVICE_ROLE_KEY}}
          SUPABASE_JWT_SECRET=${{env.SUPABASE_JWT_SECRET}}
          RESEND_API_KEY=${{env.RESEND_API_KEY}}
          FROM_EMAIL=${{env.FROM_EMAIL}}
          SUPPORT_EMAIL=${{env.SUPPORT_EMAIL}}
          DESCOPE_ISSUER=${{env.DESCOPE_ISSUER}}
          DESCOPE_AUDIENCE=${{env.DESCOPE_AUDIENCE}}
          DESCOPE_JWKS_URI=${{env.DESCOPE_JWKS_URI}}
          DESCOPE_MGMT_KEY=${{env.DESCOPE_MGMT_KEY}}
          EOF
        working-directory: ${{env.APP_DIR}}

      - name: Prepare Supabase config # Supabaseのconfig.tomlをセットアップ
        run: |
          echo "Using Supabase config for '${{env.ENVIRONMENT}}'"
          cp config.${{env.ENVIRONMENT}}.toml config.toml
        working-directory: ${{env.APP_DIR}}/supabase

      - name: Link Supabase project (non-interactive) #  Supabaseに接続
        run: |
          supabase link --project-ref "${{ env.SUPABASE_PROJECT_ID}}" \
                        --password "${{ secrets.SUPABASE_DATABASE_PASSWORD }}"
        working-directory: ${{env.APP_DIR}}/supabase

      - name: Run migrations + seed # Supabaseにマイグレーション実行 DB接続はマイグレーション用にSessionPooler（port 5432）を使用
        run: |
          supabase db push --include-seed --db-url "${{env.SUPABASE_SESSION_POOLER_URL}}"
        working-directory: ${{env.APP_DIR}}/supabase

      - name: Deploy to Vercel # Vercelへのデプロイ
        uses: amondnet/vercel-action@v20 # 内部でVercel CLIを自動インストール
        with:
          vercel-token: ${{secrets.VERCEL_TOKEN}}
          vercel-org-id: ${{secrets.VERCEL_TEAM_ID}}
          vercel-project-id: ${{secrets.VERCEL_PROJECT_ID}}
          # main または prod ブランチなら --prod を付けて本番デプロイ
          # それ以外（develop, feat-…）はプレビュー (--yes のみ)
          vercel-args: ${{(github.ref == 'refs/heads/main' || github.ref == 'refs/heads/prod') && '--prod --yes' || '--yes' }}
          working-directory: ${{env.APP_DIR}}
